sudo: false
language: node_js
go:
- 1.5.1
node_js:
- '0.12'
env:
  global:
  - CXX=g++-4.8
  - secure: raORj1tKbeT9ALJHtX1wcw5G8Tbo1epf26R0Ux83VLEYc+9BGAhHCMC2vCxjN/GssY6a5SvrkmlIL+IjxZ2JPS/0KayVrMlTuxQzHoIWxhantAghrfHgUtJeCCJIFXnZ8JU8iBN3VGG7CyECeuEiRgXp3yNoJuKyO4h1Dd0MaP+O8DSVvPGOfjL6e6rCcKaDvF1znf4+xa4wfAThan3EmUMU/xP/H5SJmb7UAX5KrcmJ6WfjBXgTYdgfL81fSNk1srk8UcivG1KTlFtVNzynIG4y6PAg0nrqftgHRZOFJSZACA0sC+j5+hSYsDyrjWXjhaEKaLV4+U8eMH0prttuKPsmzax+1onmodt3MtUBOEAg47sO6ZHmL3DZgIddsR9yID+2Y831eR9k6mpdsOZMmDFzud0kKUb1Do28KaQM8bihVlyNCEWnCTujSwkbjlxcQ2kK+n1+ekPNZsKmn8lhr8sXEA/XmvBubf4SGSL3ILPq8vPHJdzr1GByyqqR1ssHPxOopeQ45RoGluJxDiQVwPXhdiHh6iR0xom6YUvrupva4ZXHLvLPuhrRJfx1tDLif2n5cRF3yP2iLWEwMf8JZf2u2I8R4TjbNy10LzyhX3qF84Laq800c+h/jcmRhFByCDoLjgM1FaU5ikTC2XCbjr0BmfQOQkVh+3GzY0BQb6k=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
- "./install.sh"
script:
- "./build.sh"
after_success:
- "./deploy.sh"
